### PR TITLE
improved mobile navbar/sidebar

### PR DESCRIPTION
**Pull request by sweetppro**
Sidebar is hidden and all menu items moved to hamburger menu on mobile devices

desktop

mobile

### CODE REVIEW

**Comment by knadh** [comment]
Yay, this is cool! Will test locally and merge soon.

**Comment by knadh** [comment]
Checked this out locally and it works fine.

eslint throws a bunch of linting errors though. Could you please retain the indentation of the original `<b-menu-list>` from App.vue in the new Navigation.vue? They seem to have lost indentation and have become long lines. The AirBnb eslint config on the project limits line length to 120.

**Comment by sweetppro** [comment]
uggh...
my beautify plugin messes up all the formatting
It should be good now

**Comment by knadh** [comment]
Added some minor improvements to to the PR. Once you [review](https://github.com/knadh/listmonk/pull/574/commits/c147424e7eb220bbe7aefe46dfcad43c007a4cf3) and confirm, this is good to be merged.

**Review by sweetppro — COMMENTED** [review]
looks good to me

**Comment by sweetppro** [comment]
yay!

**Comment by sweetppro** [comment]
@knadh the logout button is not working on desktop in this merge, but i've fixed it in this [PR](https://github.com/knadh/listmonk/pull/580)

**Pull request merged**
