### PR TITLE
Add support for Postmark bounce notifications via webhooks

### PR DESCRIPTION
**Pull request by tosie**
_Please excuse me from not posting a feature issue first. The implementation was not that much work and I felt it would be easier to just write code and talk about that._

This PR adds support for [Postmark's bounce notifications](https://postmarkapp.com/developer/webhooks/bounce-webhook).

Currently, Listmonk has support for SES and Sendgrid bounce notifications. I use [Postmark](https://postmarkapp.com) and would like to use Listmonk, so it made sense to contribute something to this project that might be beneficial for other users, too.

There are two main areas of this PR:

1. Adding a setting to enable/disable the Postmark webhook service (including translations in the frontend).
2. Implementing a Postmark webhook service to handle bounce notifications.

There is also a migration (v2.6.0) that adds the setting key to the DB.

### CODE REVIEW

**Comment by knadh** [comment]
Thank you for the PR, @tosie. I'll review this in the next couple of weeks for the upcoming release.

**Comment by knadh** [comment]
PR looks good @tosie. One minor correction. The upcoming version is `v2.5.0`. Please remove the `v2.6.0` migration and add it to `v2.5.0` instead.

**Comment by tosie** [comment]
> PR looks good @tosie. One minor correction. The upcoming version is `v2.5.0`. Please remove the `v2.6.0` migration and add it to `v2.5.0` instead.

Done ✅

**Comment by knadh** [comment]
Thanks! Tested this. Was reviewing the Postmark docs before merging and realised that it supports [HTTP BasicAuth](https://postmarkapp.com/developer/webhooks/webhooks-overview) for webhooks. Without this, the current implementation would be open to abuse (unauthenticated POST).

**Comment by tosie** [comment]
You are right. I would try to add that, but might need help with the translations …

**Comment by knadh** [comment]
Hi @tosie. I've been experimenting with GPT-4 auto-translating missing strings in language packs using English as the base. The results are pretty good. Will finish this script and bundle in the repo soon. You can add just the English strings and leave it.

**Comment by tosie** [comment]
This PR is getting big, @knadh :-). Basic auth for Postmark webhooks is implemented now. You can take another look, if you'd like to.

**Comment by tosie** [comment]
Rebased on current master.

**Comment by knadh** [comment]
I'd made a few changes to this PR last week. Only got time to finish it just now. Could you please take a look? https://github.com/knadh/listmonk/pull/1485/commits/0289c01d1016a62b3ef81a14903714c49dda20ea

**Comment by tosie** [comment]
Your commit removes the HTTP basic auth handler completely. I'll try to re-add that to the `bounce` package (inside of the postmark handler code).

**Comment by knadh** [comment]
Ah, my bad. Added it here: https://github.com/knadh/listmonk/commit/a96b243058bcee220ca0ba1e71017754e9ad7e5d

**Comment by tosie** [comment]
Looks good 👍. Thanks!

**Comment by tosie** [comment]
Closed in favor of #1485.

**Pull request closed without merging**
