### PR TITLE
test: integrate keploy generating api tests and sql stubs

### PR DESCRIPTION
**Pull request by re-Tick**
ref: https://github.com/knadh/listmonk/issues/972

### CODE REVIEW

**Comment by knadh** [comment]
Hi @re-Tick. Whew, that's a big PR! I'll need find some free time to understand how this works and play around with it.

**Comment by re-Tick** [comment]
Sure. In Summary:
1. I am passing request context to SQL methods, so that keploy can generate the correct sql stubs for API tests. 
2. generated tests and sql stubs/mocks using keploy, currently at 49.2% coverage.
3. added a Github CI Action to run the recorded Keploy test cases
4. changed the test of Makefile to run the tests and give code coverage.

**Comment by knadh** [comment]
Hi @re-Tick, while I managed to run this and understand out how Keploy works, I'm holding off on merging this for the next release. The prod build of the `keploy` branch of the listmonk binary is 22MB as opposed to the non-Keploy `master` build which is 13MB. Any thoughts on this?

**Comment by re-Tick** [comment]
Currently, there seems to be some shared models between the Keploy's server and Go-SDK which is leading to importing all the packages of the Keploy server in the final build. 

 I'm working on a fix to ensure that the go compiler doesn't package the entire Keploy server into host application builds.

**Comment by re-Tick** [comment]
Hi @knadh, I've optimised and removed some unnecessary imports and this should optimise the size by around 3mb. After this optimisation the biggest contributor is the gRPC client libs and its used internally by keploy.

**Comment by knadh** [comment]
Hi @re-Tick. The resulting binary is now 21MB instead of 22MB.

Either way, as a general concept, I don't think it's ideal for a testing/dev library to bundle itself (especially at a significant addition to size) into production builds. Maybe a build tag based approach can be explored to stub out the heavy dependencies during build.

**Comment by re-Tick** [comment]
Hi @knadh, Thanks for the feedback. We are releasing a new version of keploy which would not need code changes to the application and generate edge cases automatically. It uses eBPF to hook into OS-level calls rather than language level methods.
I'll create a new PR once we release that :slightly_smiling_face:

**Pull request closed without merging**
