### PR TITLE
Add optional CORS header middleware

### PR DESCRIPTION
**Pull request by bgervan**
Optional CORS header middleware with configs like:

[cors]
enabled = true
allowed_origins = ["example.com"]

or with environment variable like (in docker compose for example):

```
  app:
    <<: *app-defaults
    container_name: listmonk_app
    command: [ sh, -c, "yes | ./listmonk --config config.toml" ]
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
    environment:
      - LISTMONK_cors__enabled=true
      - LISTMONK_cors__allowed_origins__0=*
      - LISTMONK_cors__allowed_origins__1=http://localhost:3000
      - LISTMONK_cors__allowed_origins__2=google.com
      - LISTMONK_cors__allowed_origins__2=another.com
```
 Note: the google.com is overriden with another.com in this example.
 
 With enabled false, everything works as before, so it doesn't break backward the compatibility. Without array of origins, it shows a warning, but works like cors disabled. 
 
 Inspiration for this PR: https://github.com/knadh/listmonk/issues/1521

### CODE REVIEW

**Comment by knadh** [comment]
Thanks for the PR @bgervan, but I don't think it's ideal for CORS configuration to be in listmonk. CORS, TLS and any other HTTP configuration is best handled in the reverse proxy that you would be using to expose listmonk to the internet, like Nginx or Caddy.

Please see my comment on the old issue: https://github.com/knadh/listmonk/issues/1523#issuecomment-1724910581

**Comment by bgervan** [comment]
> Thanks for the PR @bgervan, but I don't think it's ideal for CORS configuration to be in listmonk. CORS, TLS and any other HTTP configuration is best handled in the reverse proxy that you would be using to expose listmonk to the internet, like Nginx or Caddy.
> 
> Please see my comment on the old issue: https://github.com/knadh/listmonk/issues/1523#issuecomment-1724910581

I saw that, but it's very common to handle this on application side (in django for example).
Also on caprover the same issue mentions that it's better to handle on app side not in the nginx config. That comment made me create it optional.

In pikapod, it blocks the usage as they are not supporting cors configuration.

**Comment by knadh** [comment]
Django is a framework for building web applications, so it's natural for it to have configuration for a wide variety of HTTP related things. In fact, it is very uncommon for "consumer" web applications like listmonk to have CORS configuration.

listmonk does have built in SSL/TLS either and fully relies on a reverse proxy to provide it. Also, except for a couple of `/api/public/*` handlers, every other endpoint is private and meant to be used only with authentication.

> that it's better to handle on app side not in the nginx config

That would be incorrect. A reverse proxy like Nginx is the best place to handle config like TLS, CORS etc. transparently without having every web application build support for those.

**Comment by bgervan** [comment]
It still gives extra complexity to run nginx beside listmonk. Local docker compose too, but in case of cloudflare tunnel the ssl is handled by cloudflare, but for cors only I would need to tun a reverse proxy as well and point my tunnel to that.

Pikapod is a cheap way to run it without needing to manage, but with custom integrated form, we cannot use it.

**Comment by candidexmedia** [comment]
> Pikapod is a cheap way to run it without needing to manage, but with custom integrated form, we cannot use it.

Is this also an issue with Railway.app?

**Comment by bgervan** [comment]
> > Pikapod is a cheap way to run it without needing to manage, but with custom integrated form, we cannot use it.
> 
> Is this also an issue with Railway.app?

I am not familiar much with Railway, but if you use the docker image for the deployment without an nginx, yes.
 
https://docs.railway.app/guides/create

**Comment by candidexmedia** [comment]
> I am not familiar much with Railway, but if you use the docker image for the deployment without an nginx, yes.
> 
> https://docs.railway.app/guides/create

Looks like the latest Railway template has CORS supporr via Caddy: https://github.com/railwayapp-templates/listmonk/commit/39d3e5349fbc8c3ecfa800e8e276b393b3b66b0d#commitcomment-148663870

**Comment by ericwaetke** [comment]
I really question this decision honestly …
Especially since the solution is right here!

This cors issue renders the entire API pretty much useless. I mean, I cant even simply spin up the docker-compose locally and build my application that talks to the API because of cors.

At the _very_ least there should be a disclaimer in the main readme above the docker setup, that you cant actually use the app fully without a proxy.
Or even better, have a docker compose with a preconfigured proxy, so I can develop locally and don’t have to search through month-old issue and pull requests.

Or even better: just handle CORS in the App itself :D

**Comment by ericwaetke** [comment]
Additionally, this here: https://github.com/knadh/listmonk/issues/1521

I’m don’t know/think what you’re suggesting is even possible with a proxy like traefik. If it is, it’s above my paygrade – but as I can’t simply change what proxy we use, this is starting to become a real showstopper.

And that’s really a shame, as I love the rest of the app!

**Comment by knadh** [comment]
@ericwaetke which API endpoint are you trying to access via the browser?

**Comment by ericwaetke** [comment]
/api/subscribers

I want to basically have a form on my website where people can join the mailing list.
And ideally I’d like to statically build my website, which kind of forces me to send this request from the client.

I got a very basic caddy docker-compose setup ready though, but having multiple proxies behind each other is not my ideal hosting solution 😅

**Comment by knadh** [comment]
CORS can now be setup directly from the admin UI. Added this after increasing user demand and complains of UX-pain.

https://github.com/knadh/listmonk/commit/cdf0a5c153f4967e477bad318840726d1172184f

**Comment by duraki** [comment]
Well it was fucking time @knadh? Thanks for closing up #1521 (and resolving the issue) 🤷‍♂️ Too bad most of the gents moved out to other OSS self-hosting solutions by the time you rounded up this highly requested issue. Eh ... Cheers 🍻

**Comment by samuelsogbesan** [comment]
Hi, is there any documentation on how to configure this in the admin UI? I can't find the setting

**Comment by samuelsogbesan** [comment]
I'm guessing this also also coming in the next release

**Comment by candidexmedia** [comment]
@knadh Silly question, but what's the difference between the new CORS setting

image

and the env variable `LISTMONK_ORIGIN_0`?

Are they the same thing? Should I remove those variables and replace them with the setting? Should I be using both?

**Comment by knadh** [comment]
Hi @candidexmedia. I'm not sure where `LISTMONK_ORIGIN_0` is from. listmonk doesn't have any env var configuration for CORS, only the new feature in Settings.

**Comment by candidexmedia** [comment]
> I'm not sure where LISTMONK_ORIGIN_0 is from.

It's from here (Railway's Listmonk template):

https://github.com/railwayapp-templates/listmonk/commit/39d3e5349fbc8c3ecfa800e8e276b393b3b66b0d#comments

https://github.com/railwayapp-templates/listmonk/blob/main/Caddyfile

**Pull request closed without merging**
