### PR TITLE
Add Forward Email for smtp and bounce support

### PR DESCRIPTION
**Pull request by shaunwarman**
This PR adds Forward Email as an smtp provider as well as includes bounce support.

Relevant Forward Email documentation:
- [Send email with SMTP](https://forwardemail.net/en/faq#do-you-support-sending-email-with-smtp)
- [Bounce Webhooks](https://forwardemail.net/en/faq#do-you-support-bounce-webhooks)

**NOTE:** I did not update all of the translations. Do you have a set process or recommendation on how to update those? Translation service or some LLM?

### CODE REVIEW

**Comment by knadh** [comment]
Thanks @shaunwarman. I've a local LLM script that translates missing strings. Will run that once this is merged. Will review this PR once v4.0.0 is done (as it has a large number of breaking changes).

**Comment by knadh** [comment]
@titanism v4.x.x was released just a few days ago. I'll look into this PR in the next few days. In the meanwhile, could you please fix the merge conflicts that seem to have come up since the last release.

**Comment by knadh** [comment]
Made a few minor tweaks and added missing DB migration and language scripts. Refactored the settings to be stored in a single JSON key like Postmark which is cleaner, instead of two separate fields like SES etc (legacy).

Please test this and once you confirm, we're good to merge.

**Comment by knadh** [comment]
I'm working on v4.1.0 with a couple of bug fixes from the last release. Will release in the next 1-2 days.

**Comment by MaximilianKohler** [comment]
It's available.

**Comment by knadh** [comment]
Demo's updated to the latest version now.

**Pull request merged**
