### PR TITLE
minor: fixed errors suggested by linter

### PR DESCRIPTION
**Pull request by joicemjoseph**
Added mostly newlines.

### CODE REVIEW

**Comment by joicemjoseph** [comment]
https://github.com/knadh/listmonk/blob/0f055eacb87030b55970f4870ff3a0b22b0dcaef/models/models.go#L72

There is a redundant declaration. what to do with that?

**Comment by knadh** [comment]
Yep, it can be cleaned up.

**Comment by knadh** [comment]
Can you resolve the merge conflicts?

**Comment by knadh** [comment]
Closing stale PR. Feel free to reopen later when the latest version is rebased.

**Pull request closed without merging**
