### PR TITLE
Add MJML Support

### PR DESCRIPTION
**Pull request by natekfl**
This adds support for [MJML](https://mjml.io/). Somewhat addresses #521

As this does require the MJML CLI to be installed globally on the system (or docker container), this does somewhat break the "Single binary app" idea of listmonk. However, if the MJML CLI is not installed globally, it will simply log it in the console, and all MJML options will be hidden from the admin ui.

No worries if you feel this change is out of scope for this project due to the above.

Changes:
- Templates now have a type, which can either be HTML or MJML
- Campaign bodies have the new content type MJML. This can only be selected if the template for the campaign is also MJML
- MJML templates compile to HTML, including comment breakpoints for Outlook support
-  Added `static/email-templates/default.mjml.tpl`. While not currently used in the source code, this replicates ` static/email-templates/default.tpl` but using MJML, for reference.

### CODE REVIEW

**Comment by knadh** [comment]
Thanks for this, but you're right, `exec()`ing an external program and adding it as dependency to the core isn't ideal. I don't think we should merge this.

That said, MJML compilation should only be done once when loading the campaign / template. Here, if you have a million subscribers, mjml will be executed a million times. You should move this to maybe `manager.addCampaign()`

 https://github.com/knadh/listmonk/blob/db0bdb0a4e0fcbcd3f95074ab9eb64e250a7feec/internal/manager/manager.go#L679

**Comment by natekfl** [comment]
> You should move this to maybe `manager.addCampaign()`

Thanks for the tip there. It gets a bit weird with the order of compilation, as if the user uses go template conditionals, we want that to run on the MJML, and then the final MJML gets compiled to HTML. Compiling the MJML to HTML and then doing the go templating would result in undefined behavior for anything except just inserting variable values.

Anyway, as was discussed in #521, since there are no Go ports of MJML (at least that I know of), the only way to implement it outside of calling the global CLI tool is to use an MJML api. For that you could either use the Mailjet public api (https://mjml.io/api), which carries with it it's own privacy/security concerns, or run one on the machine (e.g. https://github.com/danihodovic/mjml-server), at which point you're basically doing the same thing as installing MJML globally. So the TL;DR is that there really isn't a better way of doing it that I know of, and like I said if that's out of scope for this project no worries, thanks anyway!

**Comment by knadh** [comment]
> Compiling the MJML to HTML and then doing the go templating would result in undefined behavior for anything except just inserting variable values.

Ah, I assumed this would be the way to do it, where MJML sits on a layer above native HTML/Go templating. MJML has a problem with `{{ the go templating syntax }}`, is it?

> is that there really isn't a better way of doing it that I know of

Looks like until a Go port of mjml is available, a seamless integration wouldn't be possible. Users will have to write mjml elsewhere and copy-paste it as HTML.

**Comment by natekfl** [comment]
> MJML has a problem with `{{ the go templating syntax }}`, is it?

It's not that it directly has a problem with the go template syntax.

For example, if you have 

```xml
<mjml>
    <mj-body>
        <mj-section>
{{if condition}}
             <mj-column>
                 Column 1
             </mj-column>
{{end}}
             <mj-column>
                 Column 2
             </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```

If you run go templating first then MJML, it will work as expected, where column 1 is only present if the condition is true.
However, if you run MJML first, then it will compile to html as if both columns are present, but one of the column `td`s will be surrounded by the go template conditional. However the second column will have the styling and breakpoints as though there are two columns, regardless of if the first column ends up being present.

Anyway, like you said this is all pretty moot since there are no good ways to include mjml in listmonk at the moment. We are currently using this fork in production, even with the subpar method, because MJML is a requirement for us. However if somehow in the future a golang port of MJML is created, we can revisit this :)

**Comment by knadh** [comment]
> Anyway, like you said this is all pretty moot since there are no good ways to include mjml in listmonk at the moment. We are currently using this fork in production, even with the subpar method, because MJML is a requirement for us. However if somehow in the future a golang port of MJML is created, we can revisit this :)

Yep. Thanks for the PR again. Closing this for now.

**Pull request closed without merging**
