### PR TITLE
Add environment variables to README.md

### PR DESCRIPTION
**Pull request by jsmith-dev**
List the runtime variables available to be passed to the Docker image.

### CODE REVIEW

**Comment by knadh** [comment]
Thanks for the PR @jsmith-dev 

I think it'd be better to add this to the Wiki instead (and the Config section can be linked from the README). I had a 

The [Developer setup](https://github.com/knadh/listmonk/wiki/Developer-setup) page mentions this in passing, but I've created a new page for for [Configuration](https://github.com/knadh/listmonk/wiki/Configuration]) where this can be detailed. Could you please add the contents of your PR there instead?

**Comment by jsmith-dev** [comment]
One of the key reasons to put this in the README.md is beacuse it puts the information directly where a user first needs it. Specifically - if you have a look at your project's image (https://hub.docker.com/r/listmonk/listmonk) this landing page is generated from the README.md and is the only thing a users sees when first evaluating your image.

**Comment by mr-karan** [comment]
> beacuse it puts the information directly where a user first needs it.

The README can contain the link to `Configuration` where the user can read all these settings. README is just a quick overview of what the project is about and really basic instructions on how to get it running. For any advanced features/concepts, a secondary page is more suited as @knadh mentioned. :+1:

**Comment by knadh** [comment]
Closing this PR. I've copied env var help doc to a Wiki page and linked it from the Docker section in the README: https://github.com/knadh/listmonk/commit/bbe239ba294c4b83def61746f274f13ee0deadcd

Thanks @jsmith-dev

**Pull request closed without merging**
