### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by NicoHood**
It would be nice if someone can double-check

### CODE REVIEW

**Comment by an0nfunc** [comment]
Looks good.

**Comment by ChrisTG742** [comment]
@NicoHood: Could it be that the line " "campaigns.testDisabled": "Enter password to test" (line 89) is deleted by accident in your PR?

**Comment by an0nfunc** [comment]
@ChrisTG742 no that's fine, see https://github.com/knadh/listmonk/issues/1039#issuecomment-1320861094

**Comment by NicoHood** [comment]
I just pasted the autogenerated json file from the online tool

**Comment by ChrisTG742** [comment]
> @ChrisTG742 no that's fine, see [#1039 (comment)](https://github.com/knadh/listmonk/issues/1039#issuecomment-1320861094)

Ah, I see. Then I'm fine with the PR, too.

**Comment by knadh** [comment]
Thanks everyone!

**Pull request merged**
