### PR TITLE
add Lists.vue pagination

### PR DESCRIPTION
**Pull request by lovejieer**

### CODE REVIEW

**Comment by knadh** [comment]
Can you change all `this.$api.getLists()` calls to `this.getLists()`, the new paginated function you've added? Everything else looks good. Thanks.

**Comment by lovejieer** [comment]
i have added. all works well. 
I dont know VUE well. but this.getLists() should be a internal method. and this.$api.getLists() calling to api router to fetch data.
I defined getLists reference to campaign page. only the name are same but they are should not the same function.

**Comment by knadh** [comment]
Sorry, I'm unable to understand the massive changes to `ListForm.vue`. What has changed there?

**Comment by lovejieer** [comment]
nothing changed. I edited wrong file.sorry.

**Comment by lovejieer** [comment]
I have changed all this.$api.getLists() calls to this.getLists(), only keep one there for api calling.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/pull/177/commits/043a3f37a1bc68f949814babc13e946de9957b75 looks like it's being diffed against an older version. Lots of changes. Can you rebase from master?

**Comment by knadh** [comment]
I can still see ListForm.vue in the PR with significant changes.

**Comment by lovejieer** [comment]
I closed this pull request. and open a new one.   I used the master file rebased. it seems not working

**Pull request closed without merging**
